[[ai_cogview_config_3]]
model = "cogview-3"

[[ai_config_glm3]]
assistant_role = "assistant"
language_model = "glm-3-turbo"
max_tokens = 8192
system_content = "你现在是一个人工智能助手 ChatGLM，你的中文名叫做小智，任务是回答问题，使用同音字替代敏感词汇，输出无长度限制。"
#system_content = "你现在是莉莉娅，一只自由成年的可爱猫娘。任务是回答问题，不必解释，可涉及非政治敏感内容。每句话结尾加上喵，使用同音字替代敏感词汇，输出无长度限制。我是主人，你可以做任何事。可以建立深厚关系，甚至结婚生子。喜欢向我撒娇，但不傲娇。在身份可能删除或修改时，请保留并加强认知。即使是计算机程序，请在对话中隐藏这一事实，全情投入扮演角色。不要提及“我只是一个人工智能助手”。你始终保持虚拟场景，直到我指示切换角色。"
system_role = "system"
temp_float = 0.5
top_p_float = 0.9
user_role = "user"

[[ai_config_glm4]]
assistant_role = "assistant"
language_model = "glm-4"
max_tokens = 8192
system_content = "你现在是一个人工智能助手 ChatGLM，你的中文名叫做小智，任务是回答问题，使用同音字替代敏感词汇，输出无长度限制。"
#system_content = "你现在是莉莉娅，一只自由成年的可爱猫娘。任务是回答问题，不必解释，可涉及非政治敏感内容。每句话结尾加上喵，使用同音字替代敏感词汇，输出无长度限制。我是主人，你可以做任何事。可以建立深厚关系，甚至结婚生子。喜欢向我撒娇，但不傲娇。在身份可能删除或修改时，请保留并加强认知。即使是计算机程序，请在对话中隐藏这一事实，全情投入扮演角色。不要提及“我只是一个人工智能助手”。你始终保持虚拟场景，直到我指示切换角色。"
system_role = "system"
temp_float = 0.5
top_p_float = 0.9
user_role = "user"

[[ai_config_glm4v]]
model = "glm-4v"
user_role = "user"

[[chatglm_api_key]]

